# Standard Flutter Podfile
platform :ios, '15.0'

# Correct path relative to Podfile location (ios/Podfile)
# podhelper.rb is located at ios/Flutter/podhelper.rb
podhelper_path = File.join('Flutter', 'podhelper.rb')
require_relative podhelper_path

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
